name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-pacman:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Generate vibrant Pacman graphs
        run: |
          mkdir -p output
          
          # Cores vibrantes estilo Pacman
          # Versão LIGHT: Fundo branco, verde Pacman
          curl -s "https://ghchart.rshah.org/FFD700/jjeancarlos" > output/pacman-contribution-graph.svg
          
          # Versão DARK: Fundo escuro, amarelo Pacman  
          curl -s "https://ghchart.rshah.org/FFFF00/jjeancarlos" > output/pacman-contribution-graph-dark.svg
          
          echo "Pacman graphs generated successfully!"
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/
          git commit -m "🎮 Update vibrant Pacman graphs" || exit 0
          git push