name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Generate contribution SVG
        run: |
          # Cria a pasta output se não existir
          mkdir -p output
          
          # Baixa o gráfico de contribuições via API
          # Formato Pacman style
          curl -o output/pacman-contribution-graph.svg \
          "https://ghchart.rshah.org/00FF00/jjeancarlos"
          
          # Versão dark
          curl -o output/pacman-contribution-graph-dark.svg \
          "https://ghchart.rshah.org/008000/jjeancarlos"
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/
          git commit -m "📈 Update Pacman contribution graph" || exit 0
          git push