name: Debug Pacman

on:
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate Pacman
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: jjeancarlos

      - name: Show current directory
        run: |
          echo "PWD:"
          pwd

      - name: List everything
        run: |
          ls -lah
          echo "-------------"
          find . -maxdepth 3

      - name: Check dist
        run: |
          if [ -d dist ]; then
            echo "dist exists"
            ls -R dist
          else
            echo "dist DOES NOT exist"
          fi
