name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Generate contribution graph
        uses: ashutosh00710/github-readme-activity-graph@v4
        with:
          username: jjeancarlos
          bg_color: 0D1117
          color: 00FF00
          line: 00FF00
          point: 00FF00
          hide_title: true
          hide_border: true
          output: output/pacman-contribution-graph.svg
          
      - name: Generate dark version
        uses: ashutosh00710/github-readme-activity-graph@v4
        with:
          username: jjeancarlos
          bg_color: 000000
          color: 00FF00
          line: 00FF00
          point: 00FF00
          hide_title: true
          hide_border: true
          output: output/pacman-contribution-graph-dark.svg
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/
          git commit -m "📈 Update contribution graphs" || exit 0
          git push