name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Generate Pacman contribution graph
        uses: jstrieb/github-stats@main
        with:
          include_private_contributions: false
          screenshots_enabled: false
          svg_enabled: true
          svg_path: output/pacman-contribution-graph.svg
          svg_dark_path: output/pacman-contribution-graph-dark.svg
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/
          git commit -m "📈 Update Pacman contribution graph" || exit 0
          git push