name: Generate Pacman Contribution Graph

on:
  schedule:
    # Roda a cada 24 horas (meia-noite UTC)
    - cron: "0 0 * * *" 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-pacman:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Crucial para o commit
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main 
          
      - name: Generate Pacman graphs 🎨
        # AÇÃO CORRIGIDA E MAIS ESTÁVEL:
        uses: pacman-graph/pacman-graph-action@v1 
        with:
          # O nome de usuário para o gráfico
          github_user: jjeancarlos
          # O caminho de saída para os arquivos SVG
          output_dir: output
          
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: output/*.svg 
          commit_message: "🎮 Update Pacman contribution graphs"