name: Generate Pacman Contribution Graph

on:
  schedule:
    # Roda a cada 24 horas (meia-noite UTC)
    - cron: "0 0 * * *" 
  # Permite execu칞칚o manual
  workflow_dispatch:
  # Roda a cada push na main (opcional, mas bom para testes)
  push:
    branches:
      - main

jobs:
  generate-pacman:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necess치rio para commitar o SVG
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # 칄 crucial que voc칡 esteja no branch onde o README est치.
          ref: main 
          
      - name: Generate Pacman graphs 游꿛
        # A칞칚o que gera o gr치fico do Pacman
        uses: L-P/pacman-contrib@master 
        with:
          # O nome de usu치rio deve ser passado para que a a칞칚o saiba qual gr치fico usar.
          # Substitua 'jjeancarlos' pelo seu nome de usu치rio se o seu README n칚o estiver neste reposit칩rio.
          GITHUB_USERNAME: jjeancarlos 
          # Definindo os caminhos de sa칤da, como voc칡 usa no seu README.
          OUTPUT_PATH: output/pacman-contribution-graph.svg
          DARK_OUTPUT_PATH: output/pacman-contribution-graph-dark.svg
          
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Garante que apenas os arquivos gerados no diret칩rio 'output' sejam commitados.
          file_pattern: output/*.svg 
          commit_message: "游꿡 Update Pacman contribution graphs"