name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Generate GitHub contribution graph
        uses: DemuraAIdev/github-contribution-snake-animation@v0.0.4
        with:
          # Suas configurações
          github_user_name: jjeancarlos
          # Arquivos de saída - vamos usar o mesmo formato do Pacman
          svg_out_path: output/pacman-contribution-graph.svg
          dark_svg_out_path: output/pacman-contribution-graph-dark.svg
          # Estilo do gráfico (pode ajustar)
          graph_type: classic
          # Cores (opcional)
          color_snake: "#00FF00"
          color_dots: "#008000"
          color_dots_min: "#004d00"
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/
          git commit -m "📈 Update Pacman contribution graph" || exit 0
          git push