name: Generate Pacman Contribution Graph

on:
  schedule:
    # Roda a cada 24 horas (meia-noite UTC)
    - cron: "0 0 * * *" 
  # Permite execução manual
  workflow_dispatch:
  # Roda a cada push na main (opcional)
  push:
    branches:
      - main

jobs:
  generate-pacman:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessário para commitar o SVG
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main 
          
      - name: Generate Pacman graphs 🎨
        # AÇÃO CORRIGIDA: Nova ação de geração do Pacman
        uses: BexTuyet/pacman-graph-generator@v1
        with:
          # O nome de usuário para o gráfico
          github_user: jjeancarlos
          # Caminho onde os SVGs serão salvos, como você usa no README
          output_dir: output
          
      - name: Commit and push changes
        # Usando uma ação para simplificar o commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: output/*.svg 
          commit_message: "🎮 Update Pacman contribution graphs"