name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: jjeancarlos
          outputs: |
            output/github-snake.svg
            output/github-snake-dark.svg?palette=github-dark
          
      - name: Commit and push snake animation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/
          git commit -m "🐍 Update snake animation" || exit 0
          git push